#Semana 2: Refactorización y mejora del sistema del Parque 🎢
#El Parque de Diversiones PythonLand quiere mejorar su sistema de gestión.
#Actualmente, el programa permite registrar un visitante, consultar qué atracciones puede usar y calcular el
#costo de su visita.
#En esta práctica se debe:
#1. Refactorización en funciones
#● Crear funciones para:
#○ mostrar_atracciones() → muestra el menú de atracciones.
#○ puede_subir(edad, atraccion) → devuelve True/False según si puede acceder a la atracción.
#○ calcular_precio(atraccion) → devuelve el precio de la atracción.
#○ registrar_visita() → pide datos del visitante, procesa las atracciones elegidas y retorna el
#resumen.
#○ mostrar_resumen(resumen) → imprime en pantalla la información del visitante.

#2. Modularización
#● Guardar el código en dos archivos:
#○ main.py (ejecución principal).
#○ parque.py (donde van las funciones).
#3. Paquete
#● Crear un paquete llamado gestion_parque y dentro incluir parque.py.
#● El main.py debe importar desde el paquete.
#4. Colores con colorama
#● Instalar un entorno virtual con venv.
#● Instalar la librería colorama.
#● Usar colores en la salida (ejemplo: mensajes de error en rojo, éxito en verde, menú en amarillo).
#5. Nueva funcionalidad
#● Agregar la opción de calcular un descuento del 10% si el visitante compra 3 o más atracciones.
